### PR TITLE
Upgraded bpi version

### PR DESCRIPTION
**Pull request by bladyjoker**
Waiting on the local checks to finish

### CODE REVIEW

**Comment by bladyjoker** [comment]
Hi @gege251 sorry for the hercules-ci stuff being red, recently these things started popping up in my PRs and I still don't know how to get rid of it

**Comment by gege251** [comment]
@bladyjoker I just merged a PR from Marton with the correct Hercules setup, hopefully it solves the problem

**Comment by bladyjoker** [comment]
> @bladyjoker I just merged a PR from Marton with the correct Hercules setup, hopefully it solves the problem

Sorry @gege251 for the mess, I suspected it's related to my setup, but perhaps it's not?

**Comment by gege251** [comment]
TBH I'm still not familiar with Hercules-CI, but I'll try to reevaluate this somehow.

**Review by gege251 — APPROVED** [review]
It works now

**Pull request merged**
