### PR TITLE
Add GitHub CI

### PR DESCRIPTION
**Pull request by L-as**
I'm not sure this works TBH

### CODE REVIEW

**Review by gege251 — APPROVED** [review]
Looking good to me. Let's merge it, and see how it goes.

**Comment by gege251** [comment]
I just remembered, that we still have some issue with nix builds, but @aske is already working on that.

**Comment by L-as** [comment]
I'm currently working on this with @MangoIV  as part of my work on plutus-scaffold

**Comment by mikekeke** [comment]
Should linting and formatting checks also be added?

**Comment by L-as** [comment]
That should be part of the .check attribute

**Comment by L-as** [comment]
Any chance this could be merged?

**Comment by mikekeke** [comment]
@L-as Sure! Thanks!

**Comment by mikekeke** [comment]
@zygomeb looks like `CACHIXKEY` is not set, and I have no access to settings.

**Comment by mikekeke** [comment]
Fails with error now:
`error: input 'cardano-node/nixpkgs' follows a non-existent input 'haskellNix/nixpkgs-2105'`

**Comment by L-as** [comment]
I'll update the version of Nix used by CI.

**Pull request merged**
