### PR TITLE
Update BPI

### PR DESCRIPTION
**Pull request by samuelWilliams99**

### CODE REVIEW

**Comment by IAmPara0x** [comment]
The tests are failing because, the collateral utxo is not taken into account.

```     
  Value assertion failed on own wallet:
        Expected: 44707600 lovelace
        Got: 34561400 lovelace
```

The difference between got and expected is exactly `10Ada`, which is the value of collateral utxo. To confirm this feel free to change the `pcCollateralSize`.

**Comment by samuelWilliams99** [comment]
Yep, we'll need to adjust for this, this PR was mostly just to get BPI updated quickly.
@nazrhom will you have time to take a look at the tests?

**Comment by IAmPara0x** [comment]
@samuelWilliams99 I have managed to fix the failing tests, as expected I had to take collateral Value and it's fee into account https://github.com/mlabs-haskell/plutip/pull/100 . But I think it's more of a temporary solution, the better solution will be creating the collateral  utxo automatically when initializing the wallet, i.e. every wallet will come with it's own `initAda` and collateral utxo

**Comment by nazrhom** [comment]
Hey @IAmPara0x I see the last test is still failing in that PR, I pushed here the changes that seem to work while running my own tests locally.

**Comment by IAmPara0x** [comment]
Those tests are failing because of a bug, that I don't think is related to collateral handling. Here's the summary of that bug:
There's sometimes a discrepancy of 7,600 lovelace, while running the same tests, i.e. when same tests are run sometimes there's 7,600 lovelace less in the wallet and sometimes everything is fine and the tests passes.

**Comment by IAmPara0x** [comment]
Please check your latest commit, it's also failing because of that bug. As said earlier, if you will run those tests more that 1 time, everything will succeed, it's kinda "random", therefore it makes hard to guess where the 7,600 lovelace goes. But, I will look into it later.

**Comment by nazrhom** [comment]
Ahh sorry, I had missed you commenting on that bug, was just noticing I am also getting this strange random behaviour.
Thanks!

**Comment by IAmPara0x** [comment]
with #100 merged there's no need for this anymore, should we close it @mikekeke ?

**Comment by mikekeke** [comment]
Closed by #100

**Pull request closed without merging**
